version: 0.2
phases:
 install:
   commands:
     - |
         #Update
         apt-get update
         #Install composer
         php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         php composer-setup.php ;
         php -r "unlink('composer-setup.php');" ;
         mv composer.phar /usr/local/bin/composer
 build:
   commands:
     - composer install
     - touch database/database.sqlite
     - php artisan migrate
